services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "9050:5000"
    volumes:
      - .:/app
    links:
      - db
    
  db:
    image: mongo:latest

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start